@base_url=http://localhost:3000

### Test APIs
GET {{base_url}}

### Create new account
POST {{base_url}}/v1/api/auth/signup
Content-Type: application/json

{
	"username": "Hoang Nguyen",
	"email": "hoang@hcmut.edu.vn",
	"password": "123456"
}

### Login 
POST {{base_url}}/v1/api/auth/login
Content-Type: application/json

{
	"email": "lam.cao1206@hcmut.edu.vn",
	"password": "123456"
}

### Logout
POST  {{base_url}}/v1/api/auth/logout

### Search
GET {{base_url}}/v1/api/user/search?q=Nguyen
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxhbS5jYW8xMjA2QGhjbXV0LmVkdS52biIsImlhdCI6MTc0MjIxNzI5MiwiZXhwIjoxNzQyMzAzNjkyfQ.V2sA6ZeaLvWigt-kJdFeo0wa1pzMCgsYp_Qml_2ACOA


### Fetch contact lists
GET {{base_url}}/v1/api/chat/contacts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxhbS5jYW8xMjA2QGhjbXV0LmVkdS52biIsImlhdCI6MTc0MjMwMjk0NywiZXhwIjoxNzQyMzg5MzQ3fQ.hb8lsytsFKlJdY2WIlYb6lOg1pqE3Siu4CEVPVAJOgQ


### Fetch users
GET {{base_url}}/v1/api/user/find
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxhbS5jYW8xMjA2QGhjbXV0LmVkdS52biIsImlhdCI6MTc0MjgxNjc2OSwiZXhwIjoxNzQyOTAzMTY5fQ.uEGD84YJMK88ZyWXKtMsDS-WRi_o0-Wz0biukGkejMI

### Fetch all incoming friend requests
GET {{base_url}}/v1/api/user/requests
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxhbS5jYW8xMjA2QGhjbXV0LmVkdS52biIsImlhdCI6MTc0MjgxNjc2OSwiZXhwIjoxNzQyOTAzMTY5fQ.uEGD84YJMK88ZyWXKtMsDS-WRi_o0-Wz0biukGkejMI

### Fetch all incoming friend requests
PUT {{base_url}}/v1/api/user/request/67e145520aa9f4ee95deee3f?action=accept
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxhbS5jYW8xMjA2QGhjbXV0LmVkdS52biIsImlhdCI6MTc0MjgxNjc2OSwiZXhwIjoxNzQyOTAzMTY5fQ.uEGD84YJMK88ZyWXKtMsDS-WRi_o0-Wz0biukGkejMI


### Fetch all contact lists
GET {{base_url}}/v1/api/chat/contacts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxhbS5jYW8xMjA2QGhjbXV0LmVkdS52biIsImlhdCI6MTc0MjkwMDQ3MywiZXhwIjoxNzQyOTg2ODczfQ.Yw5TyreoEXeE3xWyxLHz00q9xJUetcpu1FlgMNh6-ls